replicaCount: 1

image:
  repository: ghcr.io/vasyakrg/k8s-exporter
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

labels: {}
annotations: {}
serviceMonitor:
  enabled: true
  labels: {}
  annotations: {}

kubeConfig: |-
  # вставьте содержимое kubeconfig.yaml сюда
