apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-exporter.fullname" . }}-kubeconfig
  labels:
    app: {{ include "k8s-exporter.name" . }}
data:
  kube: |
    {{ .Values.kubeConfig | nindent 4 }}
