apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-exporter.fullname" . }}
  labels:
    app: {{ include "k8s-exporter.name" . }}
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.annotations }}
annotations:
{{ toYaml . | indent 2 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "k8s-exporter.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "k8s-exporter.name" . }}
    spec:
      volumes:
        - name: kubeconfig
          configMap:
            name: {{ include "k8s-exporter.fullname" . }}-kubeconfig
      containers:
      - name: k8s-exporter
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: kubeconfig
          mountPath: /app/kube
          subPath: kube
        args:
        - "--kubeconfig"
        - "/app/kube"
