apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-exporter.fullname" . }}
  labels:
    app: {{ include "k8s-exporter.name" . }}
{{- with .Values.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.annotations }}
annotations:
{{ toYaml . | indent 2 }}
{{- end }}
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: { { include "k8s-exporter.name" . } }
