apiVersion: v1
kind: Service
metadata:
  name: { { include "k8s-exporter.fullname" . } }
  labels:
    app: { { include "k8s-exporter.name" . } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: { { include "k8s-exporter.name" . } }
